# Modeling 

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('trainDataFeatures.tsv', sep='\t', index_col=0)

In [3]:
df

id  sentiment                                             review  \
0       5814_8          1  With all this stuff going down at the moment w...   
1       2381_9          1  \The Classic War of the Worlds\" by Timothy Hi...   
2       7759_3          0  The film starts with a manager (Nicholas Bell)...   
3       3630_4          0  It must be assumed that those who praised this...   
4       9495_8          1  Superbly trashy and wondrously unpretentious 8...   
5       8196_8          1  I dont know why people think this is such a ba...   
6       7166_2          0  This movie could have been very good, but come...   
7      10633_1          0  I watched this video at a friend's house. I'm ...   
8        319_1          0  A friend of mine bought this film for £1, and ...   
9      8713_10          1  <br /><br />This movie is full of references. ...   
10      2486_3          0  What happens when an army of wetbacks, towelhe...   
11     6811_10          1  Although I generally do not like remakes belie...   
12     11744_9          1  \Mr. Harvey Lights a Candle\" is anchored by a...   
13      7369_1          0  I had a feeling that after \Submerged\", this ...   
14     12081_1          0  note to George Litman, and others: the Mystery...   
15      3561_4          0  Stephen King adaptation (scripted by King hims...   
16      4489_1          0  `The Matrix' was an exciting summer blockbuste...   
17      3951_2          0  Ulli Lommel's 1980 film 'The Boogey Man' is no...   
18     3304_10          1  This movie is one among the very few Indian mo...   
19     9352_10          1  Most people, especially young people, may not ...   
20      3374_7          1  \Soylent Green\" is one of the best and most d...   
21     10782_7          1  Michael Stearns plays Mike, a sexually frustra...   
22     5414_10          1  This happy-go-luck 1939 military swashbuckler,...   
23     10492_1          0  I would love to have that two hours of my life...   
24      3350_3          0  The script for this movie was probably found i...   
25      6581_7          1  Looking for Quo Vadis at my local video store,...   
26      2203_3          0  Note to all mad scientists everywhere: if you'...   
27       689_1          0  What the ........... is this ? This must, with...   
28      9152_1          0  Intrigued by the synopsis (every gay video the...   
29      6077_1          0  Would anyone really watch this RUBBISH if it d...   
...        ...        ...                                                ...   
24970   9389_7          1  Red Rock West (1993)<br /><br />Nicolas Cage g...   
24971   9251_9          1  what can i say?, ms Erika Eleniak is my favori...   
24972  1422_10          1  The spoiler warning is for those people who wa...   
24973   7415_2          0  What do you call a horror story without horror...   
24974   7492_7          1  Though not a horror film in the traditional se...   
24975  7689_10          1  This was what black society was like before th...   
24976  12370_4          0  They probably should have called this movie Th...   
24977   5625_8          1  Attractive Marjorie(Farrah Fawcett)lives in fe...   
24978   9397_9          1  Vaguely reminiscent of great 1940's westerns, ...   
24979   5992_7          1  I admit I had no idea what to expect before vi...   
24980  2488_10          1  To me, the final scene, in which Harris respon...   
24981  9627_10          1  This is by far the funniest short made by the ...   
24982   3822_2          0  To be a Buster Keaton fan is to have your hear...   
24983   5983_4          0  I was one of those \few Americans\" that grew ...   
24984   8021_2          0  Visually disjointed and full of itself, the di...   
24985   3471_3          0  this movie had more holes than a piece of swis...   
24986  6034_10          1  Last November, I had a chance to see this film...   
24987   1988_9          1  First off, I'd like to make a correction on an...   
24988   7623

In [4]:
columns = df.columns[3:]

In [5]:
columns

Index([u'review_length', u'good', u'bad', u'interesting', u'awesome',
       u'terrible', u'amazing', u'boring', u'awful'],
      dtype='object')

In [6]:
X = np.asarray(df[columns])

In [7]:
X

array([[2302,    0,    0, ...,    3,    0,    1],
       [ 946,    0,    0, ...,    0,    0,    0],
       [2455,    0,    0, ...,    0,    0,    1],
       ..., 
       [ 641,    0,    0, ...,    0,    0,    0],
       [1145,    0,    0, ...,    0,    0,    0],
       [ 942,    0,    0, ...,    0,    0,    0]])

In [8]:
y = np.asarray(df.sentiment.transpose())

In [9]:
y

array([1, 1, 0, ..., 0, 0, 1])

In [10]:
from sklearn.naive_bayes import MultinomialNB

In [11]:
nb = MultinomialNB()

In [12]:
nb.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [13]:
nb.predict(np.asarray(df[columns]))

array([0, 1, 0, ..., 1, 1, 1])

In [14]:
np.mean(nb.predict(np.asarray(df[columns])) == df.sentiment)

0.67023999999999995

## Make Kaggle submission with test data

In [15]:
test_data = pd.read_csv('testData.tsv', sep='\t')

In [16]:
test_data

id                                             review
0      12311_10  Naturally in a film who's main themes are of m...
1        8348_2  This movie is a disaster within a disaster fil...
2        5828_4  All in all, this is a movie for kids. We saw i...
3        7186_2  Afraid of the Dark left me with the impression...
4       12128_7  A very accurate depiction of small time mob li...
5        2913_8  ...as valuable as King Tut's tomb! (OK, maybe ...
6        4396_1  This has to be one of the biggest misfires eve...
7         395_2  This is one of those movies I watched, and won...
8       10616_1  The worst movie i've seen in years (and i've s...
9        9074_9  Five medical students (Kevin Bacon, David Labr...
10       9252_3  'The Mill on the Floss' was one of the lesser ...
11       9896_9  I just saw this film at the phoenix film festi...
12        574_4  \The Love Letter\" is one of those movies that...
13      11182_8  Another fantastic offering from the Monkey Isl...
14      11656_4  This was included on the disk \Shorts: Volume ...
15       2322_4  I'm not really much of an Abbott & Costello fa...
16       8703_1  This movie was dreadful. Biblically very inacc...
17       7483_1  I don't think I've ever gave something a 1/10 ...
18      6007_10  Excellent story-telling and cinematography. Po...
19      12424_4  I completely forgot that I'd seen this within ...
20       4672_1  I like action movies. I have a softspot for \B...
21      10841_3  This is one of the worst Sandra Bullock movie ...
22       8954_7  Watched this flick on Saturday afternoon cable...
23       7392_1  I went to see \TKIA\" with high expectations, ...
24      10288_8  All credit to writer/director Gilles Mimouni w...
25       5343_4  As a writing teacher, there are two ending I n...
26       4950_1  I don't know why this has gotten any decent re...
27       9257_4  This film was released in the UK under the nam...
28       8689_3  Uncle Fred Olen Ray once again gives us a litt...
29       4480_2  OK, it's watchable if you are sick in bed or h...
...         ...                                                ...
24970   6857_10  With \Anatomy\" the german film producers have...
24971   11091_8  This movie is one of my all-time favorites. I ...
24972    4167_2  I found Code 46 very disappointing. I thought ...
24973     679_4  Tamara Anderson and her family are moving once...
24974   10147_1  Now I've seen it all. Just when I thought it c...
24975    6875_1  In this movie everything possible was wrong an...
24976    923_10  Well every scene so perfectly presented. Never...
24977    6200_8  Sleeper Cell is what 24 should have been. 24 i...
24978    7208_8  Not for everyone, but I really like it. Nice e...
24979    5363_8  Set just before the Second World War, this is ...
24980    4067_8  Contains Spoiler The movie is a good action/co...
24981    1773_7  This is one of several period sea-faring yarns...
24982   1498_10  Hearkening back to those \Good Old Days\" of 1...
24983  10497_10  I thought this to be a pretty good example of ...
24984   3444_10  Seeing this film, or rather set of films, in m...
24985     588_2  I didn't like this movie for many reasons - VE...
24986    9678_9  I absolutely love this show!!!!!!!, Its basica...
24987    1983_9  eXistenZ combines director David Cronenberg's ...
24988    5012_3  this movie is allegedly a comedy.so where did ...
24989   12240_2  The Comebacks is a spoof on inspirational spor...
24990    5071_2  I'd love to write a little summary of this mov...
24991    5078_2  Obvious tailored vehicle for Ryan Philippe. It...
24992   10069_3  <br /><br />JURASSIC PARK III *___ Adventure <...
24993    7407_8  If you're even mildly interested in the War be...
24994    7207_1  It used to be that video distributors like Sub...
24995   2155_10  Sony Pictures Classics, I'm looking at you! So...
24996     59_10  I always felt that Ms. Merkerson had never got...
24997    2531_1  I was so disappointed in this movie. I am v

In [17]:
test_data['review_length'] = test_data.review.apply(len)

In [18]:
# Do the same feature extraction with the test data

from sklearn.feature_extraction.text import CountVectorizer
vocab_expand = ['awesome', 'good', 'amazing', 'interesting', 'terrible', 'bad', 'awful','boring']
expand_vectorizer = CountVectorizer(vocabulary=vocab_expand)
bow_expand = expand_vectorizer.fit_transform(test_data.review).todense()
words_expand = list(expand_vectorizer.vocabulary_.keys())
bow_expand_df = pd.DataFrame(bow_expand, index=test_data.index, columns = words_expand)
test_data_expand = test_data.join(bow_expand_df)
test_data_expand.to_csv('testDataFeatures.tsv', sep='\t')

In [19]:
predictions = nb.predict(np.asarray(test_data_expand[columns]))

In [20]:
submission = pd.DataFrame({"id": test_data.id, "sentiment": predictions})

In [21]:
submission.to_csv('submission_kaggle.tsv', sep='\t')

In [22]:
!ls

0-Exploration.ipynb        labeledTrainData.tsv
1-Feature_extraction.ipynb submission_kaggle.tsv
2-Modeling.ipynb           testData.tsv
3-Validation.ipynb         testDataFeatures.tsv
4-Ensemble.ipynb           trainDataFeatures.tsv
README.md                  trainDataFeatures2.tsv
environment.yml
