# Ensemble

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Data preparation
data = pd.read_csv('trainDataFeatures.tsv', sep='\t', index_col=0)

columns = data.columns[3:]
X = np.asarray(data[columns])
y = np.asarray(data.sentiment.transpose())

from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [3]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(min_samples_leaf = 10, min_samples_split = 10)

rf.fit(X=X_train, y = y_train)
y_predict = rf.predict(X_test)

In [4]:
y_predict

array([0, 1, 0, ..., 0, 0, 1])

In [5]:
from sklearn.metrics import roc_auc_score, confusion_matrix

roc_auc_score(y_test, y_predict)

0.63702941296956284

In [6]:
confusion_matrix(y_test, y_predict)

array([[1811, 1279],
       [ 986, 2174]])

In [7]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(min_samples_leaf = 2, min_samples_split = 2)

rf.fit(X=X_train, y = y_train)
y_predict = rf.predict(X_test)
roc_auc_score(y_test, y_predict)

0.61749877104584006

In [8]:
confusion_matrix(y_test, y_predict)

array([[1836, 1254],
       [1135, 2025]])

In [9]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(min_samples_leaf = 1, min_samples_split = 1)

rf.fit(X=X_train, y = y_train)
y_predict = rf.predict(X_test)
roc_auc_score(y_test, y_predict)

0.59560597681373151

In [10]:
confusion_matrix(y_test, y_predict)

array([[1820, 1270],
       [1257, 1903]])